/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Inc/main.h"




PinConfig_t portc_13 = {.port = PORTC , .pin = PIN13 , .mode = OUTPUT , .outType = PUSH_BULL , .speed = MEDUIM_SPEED , .pullType = NO_PULL};

int main(void)
{


	SystemClock_Config();

	RCC_GPIOC_CLK_ENABLE();
	gpio_pin_init(&portc_13);

	gpio_set_pin_value(PORTC, PIN13, PIN_HIGH);
	gpio_set_pin_value(PORTC, PIN13, PIN_LOW);

	gpio_toggle_pin_value(PORTC, PIN13);
	gpio_toggle_pin_value(PORTC, PIN13);
	gpio_toggle_pin_value(PORTC, PIN13);



    /* Loop forever */
	while(1)
	{







	}










	return 0;
}



Std_RetType_t SystemClock_Config(void)
{

	Std_RetType_t ret = RET_OK;
	RCC_OscInitTypedef RCC_OscInit ={0};
	RCC_ClkInitTypedef RCC_ClkInit ={0};

	RCC_OscInit.OscillatorType = RCC_OSCILLATORTYPE_HSI;
//	RCC_OscInit.PLL_Source_MUX = RCC_PLL_SRC_HSE;
//	RCC_OscInit.PLLMClkDivider = RCC_PLLCFGR_PLLM_DIV8;
//	RCC_OscInit.PLLPClkDivider = RCC_PLLCFGR_PLLP_DIV2;
//	RCC_OscInit.PLLNMultiplicationFactor = RCC_PLLCFGR_PLLN_TIMES_84;

	ret = HALL_RCC_OscConfig(&RCC_OscInit);

	RCC_ClkInit.AHBClkDivider  =RCC_SYSCLK_AHB_DIV1;
	RCC_ClkInit.APB1ClkDivider =RCC_HCLK_APB1_DIV1;
	RCC_ClkInit.APB2ClkDivider =RCC_HCLK_APB2_DIV1;
	ret = HALL_RCC_ClockConfig(&RCC_ClkInit);
	return ret;
}




